# Generated by Django 4.1.4 on 2023-01-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_create_at_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
