# Generated by Django 4.1.4 on 2023-01-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_image_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
