# Generated by Django 4.1.4 on 2023-01-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.CharField(default='title', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_title',
            field=models.CharField(default='price', max_length=600),
            preserve_default=False,
        ),
    ]
