# Generated by Django 4.1.4 on 2023-01-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contact_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(default='127', max_length=600),
            preserve_default=False,
        ),
    ]
