# Generated by Django 4.1.4 on 2023-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='image.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
