# Generated by Django 4.1.4 on 2023-01-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_contactdata_working_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=1000)),
                ('bot_token', models.CharField(max_length=1000)),
            ],
        ),
    ]
